spring:
  profiles:
    default: dev
    active: dev
  config:
    import: "file:secrets.yaml"
  application:
    name: application
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.mysql.dialect
      format-sql: true
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: ${mq.username}
    password: ${mq.password}
logging:
  level:
    "[org.springframework.security]": TRACE
