spring:
  profiles:
    default: dev
    active: dev
  config:
    import: "file:secrets.yaml"
  application:
    name: application
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[order_inserts]': true
        '[order_updates]': true
        jdbc:
          '[batch_size]': 50
      dialect: org.hibernate.dialect.mysql.dialect
      format-sql: true
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: ${mq.username}
    password: ${mq.password}
logging:
  file:
    name: logs/app.log
    path: logs